### ISSUE TITLE
Add Different Patterns

### ISSUE THREAD

**Issue by gautam32** [gautam32/Patterns#1]
Fork or clone the repo go to the folder of the language you will use (if the folder is not there, create one), add your file and put its details in the markdown file of your folder(with an image of an example of the pattern) and create a PR.

Note: Adding details of your pattern with an image to the markdown file is a must.

**Comment by gautam32** [comment]
> I want to contribute to this . I will make them in CPlusPlus language.

OK, check out the Python folder for reference. Create a folder C++, add a folder 'Images,' README.md, and your code to it, and create a PR

**Comment by Sanket1308** [comment]
I want to work on this. I will pattern programs in Python3.

**Comment by Kevinjadia** [comment]
@gautam32  can you assign me this issue?

**Comment by nayanapardhekar** [comment]
I have submitted the PR please accept it soon.

**Comment by gautam32** [comment]
> @gautam32 can you assign me this issue ASAP, please? I've done a pattern in python

You can start working, just create a PR whenever you feel all necessary changes are done by your side. I'll review your PR and ask if any changes will be required.

**Comment by oneamanish** [comment]
see my pull req.
